### ISSUE TITLE
Add a case over time graph

### ISSUE THREAD

**Issue by yowmamasita** [WarenGonzaga/covid19-tracker-cli#1]
Like worldometer, preferably both linear and logarithmic graphs, but linear is enough

**Comment by WarenGonzaga** [comment]
@yowmamasita I'm thinking also of adding a graph... looking for some alternative way to show it on CLI.

**Comment by WarenGonzaga** [comment]
@yowmamasita thanks for the suggestion I will study this and will give some updates...

**Comment by ianvizarra** [comment]
@WarenGonzaga  @yowmamasita https://github.com/kroitor/asciichart
This is the closest chart library I could find for generating charts in the console. Do you have any recommendations?

**Comment by WarenGonzaga** [comment]
> @WarenGonzaga @yowmamasita https://github.com/kroitor/asciichart
> This is the closest chart library I could find for generating charts in the console. Do you have any recommendations?

Thank you, I'll take a look on this...

**Comment by ianvizarra** [comment]
I created another endpoint for the historical graph. My initial plan was to add this to the existing endpoints but that will require an additional API call. It would be nice if the historical API supports ISO 3166-1 and include a summary of cases, deaths, active and recovered stats.

`https://corona.lmao.ninja/v2/historical`

@WarenGonzaga Any suggestions here before I create a PR?

<img width="672" alt="Screen Shot 2020-03-29 at 3 23 25 PM" src="https://user-images.githubusercontent.com/2890710/77843596-4badb400-71d1-11ea-979b-51891c525dac.png">

**Comment by WarenGonzaga** [comment]
@ianvizarra I love to see that on version 3 you're timing... anyway.. why is it uppercase?
PHILIPPINES should be Philippines. This is for consistency.

I like the new endpoint/route on the tracker... let do it.

**Comment by WarenGonzaga** [comment]
@ianvizarra how about something like this?

url/history/philippines/ or /all --> return national stats (is it possible to mix all of it in a graph?)

by specified endpoint...
url/history/philippines/cases
url/history/philippines/deaths
url/history/philippines/recovered
etc...

This is to avoid too much display in user's command line... let's limit it.

**Comment by WarenGonzaga** [comment]
@ianvizarra I would suggest submit the PR on dev branch.

**Comment by ianvizarra** [comment]
@WarenGonzaga 
>PHILIPPINES should be Philippines. This is for consistency.

Noted on this.

>url/history/philippines/ or /all --> return national stats (is it possible to mix all of it in a graph?)

I can mix it's summary stats but the `/all` is not yet supported in the historical API

>url/history/philippines/cases
url/history/philippines/deaths
url/history/philippines/recovered

as of now only `cases` and `deaths` are available in the `v2/historical` API

**Comment by ianvizarra** [comment]
> @ianvizarra I would suggest submit the PR on dev branch.

Noted. Just like my previous PR. gitflow approach

**Comment by WarenGonzaga** [comment]
@ianvizarra 
> I can mix it's summary stats but the /all is not yet supported in the historical API

Nope, I mean this is our endpoint... just mix the data from NovelCOVID API...

**Comment by WarenGonzaga** [comment]
@ianvizarra 
> I can mix it's summary stats but the /all is not yet supported in the historical API

Nope, I mean this is our endpoint... just mix the data from NovelCOVID API...

**Comment by ianvizarra** [comment]
>Nope, I mean this is our endpoint... just mix the data from NovelCOVID API...
>url/history/philippines/

@WarenGonzaga Yes, I can mix the national stats with the graph so that means calling these APIs together
```https://corona.lmao.ninja/countries/:country``` and
```https://corona.lmao.ninja/v2/historical/:country```. Did I get it right? 😄 

However, ```url/history/all``` will not be possible for now.

**Comment by WarenGonzaga** [comment]
> > Nope, I mean this is our endpoint... just mix the data from NovelCOVID API...
> > url/history/philippines/
> 
> @WarenGonzaga Yes, I can mix the national stats with the graph so that means calling these APIs together
> `https://corona.lmao.ninja/countries/:country` and
> `https://corona.lmao.ninja/v2/historical/:country`. Did I get it right? 😄
> 
> However, `url/history/all` will not be possible for now.

What I mean is this...
url/history/philippines/ = covid19tracker.xyz/history/philippines || covid19tracker.xyz/history/philippines/all

Not the API itself... yeah use the API I'm talking about our endpoint. Is that possible?

**Comment by ianvizarra** [comment]
@WarenGonzaga 

<img width="643" alt="Screen Shot 2020-03-29 at 4 56 04 PM" src="https://user-images.githubusercontent.com/2890710/77845056-5ae72e80-71de-11ea-9e3d-255032f11ffc.png">

**Comment by WarenGonzaga** [comment]
@ianvizarra I like the idea!

**Comment by WarenGonzaga** [comment]
We will close this as it is available on dev branch... expect the release on v3
