### ISSUE TITLE
Formatting on Windows CMD

### ISSUE THREAD

**Issue by AdamKearn** [WarenGonzaga/covid19-tracker-cli#10]
When I tried running the command I was getting this issue.
The command works fine on Linux.

Nice project!

![image](https://user-images.githubusercontent.com/30593259/77761148-795af780-702f-11ea-85ba-0f6d22dd2607.png)

**Comment by WarenGonzaga** [comment]
Did you try to append /cmd ? ex. curl https://covid19tracker.xyz/cmd

**Comment by WarenGonzaga** [comment]
@AdamKearn can I close this one?

**Comment by AdamKearn** [comment]
Yep,  all is good now.
Thanks.

Nice work on the project too.
