### ISSUE TITLE
the website is down

### ISSUE THREAD

**Issue by Asternitix** [WarenGonzaga/covid19-tracker-cli#14]
curl: (60) SSL: no alternative certificate subject name matches target host name 'covid19tracker.xyz'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

please fix. I enjoy the service.

**Comment by WarenGonzaga** [comment]
Hi @Asternitix, sorry for any inconvenience this may cause to you. Everyone loves the tool but suddenly the domain name has been flagged by the domain registrar with serverHold. The server is up and running but the domain name is down I mean not resolving.

I will buy a new domain right now to get back it online... 
Follow me on twitter and facebook for any instant update regarding the tool.
Look for #covid19trackercli

https://www.facebook.com/hashtag/covid19trackercli
https://twitter.com/hashtag/covid19trackercli

Thank you for using my curl-based app...

**Comment by Asternitix** [comment]
the tildeverse thanks you, especially tilde.club

**Comment by deepend-tildeclub** [comment]
is it accessible via IP?

**Comment by Asternitix** [comment]
I hope it is

**Comment by WarenGonzaga** [comment]
@Asternitix @deepend-tildeclub do you want to access it via IP?

**Comment by Asternitix** [comment]
yes

**Comment by deepend-tildeclub** [comment]
please.. we use it in a bash script for users to show the stats

**Comment by Asternitix** [comment]
that way if that jerk does it again, our community doesn't suffer an outage and we, @deepend-tildeclub, doesn't have to change the bash script again

**Comment by WarenGonzaga** [comment]
@Asternitix @deepend-tildeclub got it so you are using the program. Thank you! Let me work on it first... so we can back online as fast as possible. We lost so much traffic....

**Comment by WarenGonzaga** [comment]
Here's the new domain name: https://trackercli.com it is not final... the historical chart having issues I'm gonna fix it tomorrow. For now you can use that domain...

This would be the final URL https://trackercli.com/covid19

@Asternitix @deepend-tildeclub

**Comment by Asternitix** [comment]
thank you.

**Comment by Asternitix** [comment]
@WarenGonzaga  there's a 502 error

**Comment by WarenGonzaga** [comment]
@Asternitix which domain you use? https://trackercli.com/covid19 is not available at the moment please use https://trackercli.com only.

**Comment by Asternitix** [comment]
trackercli.com works when used with curl, but not as a website.

**Comment by WarenGonzaga** [comment]
> trackercli.com works when used with curl, but not as a website.

Yeah, no website for now... I'm still working on static version... that domain is for backup since our mother domain is down. I'm gonna improve it as I have time.

**Comment by Asternitix** [comment]
ok, at least curl works.

**Comment by WarenGonzaga** [comment]
> ok, at least curl works.

Yes for now... don't worry we will improve this as time goes by... thank you for using my project.
