### ISSUE TITLE
Host Unreachable

### ISSUE THREAD

**Issue by mathi-ryte** [WarenGonzaga/covid19-tracker-cli#15]
➜ curl https://covid19tracker.xyz
curl: (6) Could not resolve host: covid19tracker.xyz

**Comment by WarenGonzaga** [comment]
Hi @mathi-ryte we move our domain name here: trackercli.com
The domain name has been reported as abusive and I don't know why...

**Comment by AlaaMansourTW** [comment]
Hello! Thanks for the effort :)

I tried:
`curl trackercli.com` and
`curl trackercli.com/germany`

But I get nothing, you don't have to answer here if you'll update the readme :)

Cheers!

**Comment by WarenGonzaga** [comment]
@AlaaMansourTW please append it with "https" something like this
```curl https://trackercli.com```

We don't have much time to update the readme... I'm currently busy on some local projects.
Follow me on [twitter](twitter.com/hashtag/covid19trackercli) or [facebook](facebook.com/hashtag/covid19trackercli) for project related updates.

Cheers!

**Comment by AlaaMansourTW** [comment]
Thanks for getting back to me on such short notice, if it's ok with you I can do a pull request for the read me. let me know if that helps

**Comment by WarenGonzaga** [comment]
@AlaaMansourTW yes please do it first on ```dev``` branch and I'll ask @ianvizarra to review it.

**Comment by AlaaSaadAbdo** [comment]
Done

**Comment by AlaaMansourTW** [comment]
Done

**Comment by flarn2006** [comment]
I'm not understanding; someone reported the domain as abusive and the registrar just removed it without actually checking?

**Comment by WarenGonzaga** [comment]
> I'm not understanding; someone reported the domain as abusive and the registrar just removed it without actually checking?

Yes! Do you want a proof?

**Comment by flarn2006** [comment]
I believe you, but I am interested in seeing.

**Comment by WarenGonzaga** [comment]
@flarn2006 here's the proof.

https://gen.xyz/account/submitticket.php?action=unsuspend

Look up for the domain and you'see the reason... I don't know why it is reported as abusive which is not. Many people relying on the app. What happen to earth? Those bastards should die first...

**Comment by WarenGonzaga** [comment]
Hi guys, I just created a discord channel for this project so every get the latest updates about the project. Thank you! https://discord.gg/6Gzxwtt

**Comment by WarenGonzaga** [comment]
Hi guys, @mathi-ryte @AlaaMansourTW @flarn2006 @tanuck I'm gonna close this one as we have the new domain name. Thank you!
