### ISSUE TITLE
History not working

### ISSUE THREAD

**Issue by revirevy** [WarenGonzaga/covid19-tracker-cli#22]
Hello
Using the /history feature get this:
The connection to the origin web server was made, but the origin web server timed out before responding. The likely cause is an overloaded background task, database or application, stressing the resources on your web server. To resolve, please work with your hosting provider or web development team to free up resources for your database or overloaded application

"https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524"
Additional troubleshooting information here.

**Comment by WarenGonzaga** [comment]
Hello @revirevy, we moved to a new provider... 
please use this domain name ``covid19.trackercli.com`` the ``trackercli.com`` will be using for static website. If you want to follow the development you can join to our official discord server.

https://discord.gg/6Gzxwtt

Cheers!

**Comment by WarenGonzaga** [comment]
@revirevy I'm gonna close this please check the newest readme file thanks...
