### ISSUE TITLE
Strange problem under windows 10

### ISSUE THREAD

**Issue by luke1961** [WarenGonzaga/covid19-tracker-cli#31]
It displays nearly perfectly under windows 10 if you run the tracker as follows:

chcp 65001
curl -s -L covid19.trackercli.com/history/us>tth.txt
type tth.txt

![tth](https://user-images.githubusercontent.com/6032592/78408328-d416c500-75d4-11ea-94d9-ea772b562bd9.jpg)

You see some funny/garbage characters causing the frames to become uneven. I have spent a couple of hours looking at the escape sequences produced by your website but I do not see anything wrong. Any ideas?

**Comment by WarenGonzaga** [comment]
@luke1961 Thank you for reporting... this is a known issue with the table we are using... for best experience... use the tracker under linux terminal... (ubuntu) on windows we advice everyone to append your URL with /cmd for the plain version.

**Comment by luke1961** [comment]
Thank you for responding. I got the issue resolved. Your website is fine. Windows ‘type’ command has an issue with non-ASCII characters on internal 512-byte buffer boundary. Use something like ‘cat’ command instead and everything will display fine under Windows, too.

**Comment by WarenGonzaga** [comment]
Alright cool! Thank you for letting us know...
