### ISSUE TITLE
Finds wrong country

### ISSUE THREAD

**Issue by ManuelBarrioLinares** [WarenGonzaga/covid19-tracker-cli#7]
curl https://covid19tracker.xyz/ar

expected "Argentina" as of **iso3166** but it shows Denmark.
![Screenshot_2020-03-27_01-16-04](https://user-images.githubusercontent.com/3720020/77721152-c35cc280-6fc8-11ea-8f86-9c71c868a51e.jpg)

**Comment by WarenGonzaga** [comment]
@ManuelBarrioLinares got it thanks for reporting! I'll let you know once it is fixed.

**Comment by BenAlexanderAU** [comment]
Adding on to this...

`curl https://covid19tracker.xyz/au`

expected "Australia as of iso3166 but it shows Austria.

**Comment by WarenGonzaga** [comment]
@BenAlexanderAU can you try it again, as the API developer its already fixed.

**Comment by BenAlexanderAU** [comment]
> @BenAlexanderAU can you try it again, as the API developer its already fixed.

Still returns details for Austria

**Comment by WarenGonzaga** [comment]
Thank you for your report @BenAlexanderAU I'm coordinating with the API developers. Thank you!

**Comment by cpnfeeny** [comment]
/de shows Sweden; it should show Germany
/ge shows Germany; it should show Georgia

**Comment by WarenGonzaga** [comment]
@cpnfeeny thank you! I'll fix it...

**Comment by aesycos** [comment]
I don't believe the API is designed to be used by ISO3166-1 country codes, but instead full country name, the API is actually here [corona.lmao.ninja](https://corona.lmao.ninja/) a.k.a [NovelCOVID/API](https://github.com/NovelCOVID/API) and the API Endpoint is defined as:
> **GET Request:**
`https://corona.lmao.ninja/countries/{country-name}`
**Output:**
 Returns data of a specific country. If an exact name match is desired pass ?strict=true in the query string

**Comment by WarenGonzaga** [comment]
@aesycos I contacted the developers at NovelCOVID and they said that the API don't served ISO 3166 code. In short, it returns the most related to your query. I'm working on adding the feature to the CLI. I don't want to wait for them to implement that. That's my mistake... I assume that the API supports ISO 3166.

**Comment by aesycos** [comment]
@WarenGonzaga I pushed a script to my fork of your project and a json file under lib one is a node file that takes an iso-3661 code and retrieves the countries code. I dotnt really know javascript or nodejs so im sure it could be alot better but it works. so basically `node test.js [ISO-366-1 Code]` i.e. `node test.js AR` output "Argentina"

**Comment by WarenGonzaga** [comment]
> @WarenGonzaga I pushed a [script](https://github.com/aesycos/covid19-tracker-cli/blob/master/lib/countryData/test.js) to my fork of your project and a [json file ](https://github.com/aesycos/covid19-tracker-cli/blob/master/lib/countryData/countryCodeData.json)under lib one is a node file that takes an iso-3661 code and retrieves the countries code. I dotnt really know javascript or nodejs so im sure it could be alot better but it works. so basically `node test.js [ISO-366-1 Code]` i.e. `node test.js AR` output "Argentina" maybe you can use these
> 
> Also not to create another issue, but the time reported isn't local timezone, so you should look into adjusting the time to someone's current timezone or posting the timezone of the reported cases

Thank you for the effort I will take a look, but currently I have script for that using live API for all countries... I will give some updates later...

**Comment by ak-42** [comment]
I see you're already handling it, but `curl https://covid19tracker.xyz/hr` results in Bahrain, should be Croatia.

**Comment by WarenGonzaga** [comment]
@ak-42 thanks for reporting...

**Comment by WarenGonzaga** [comment]
@ManuelBarrioLinares @ak-42 @aesycos @BenAlexanderAU @cpnfeeny 

The API Devs fixed the issue and now they support the ISO-2 and ISO-3 code... so you may now use it.
Upon checking, the AU is now pointing to Australia... please check thanks...

**Comment by BenAlexanderAU** [comment]
>  Upon checking, the AU is now pointing to Australia... please check thanks...

Confirm AU is working. Thanks for fixing this.

**Comment by WarenGonzaga** [comment]
@BenAlexanderAU thanks to the API devs for working on the fix... thank you for your effort to report the issue. I will close this now.
