### ISSUE TITLE
Stop copy/pasting

### ISSUE THREAD

**Issue by ahmadawais** [WarenGonzaga/covid19-tracker-cli#9]
You've copy pasted the description from my [CLI](https://github.com/ahmadawais/corona-cli) and the sources section word for word. Don't do that. If you can code your own projects you can write your own info. That just looks bad!

**Comment by WarenGonzaga** [comment]
OKAY, I will revise... you are too sensitive...

**Comment by WarenGonzaga** [comment]
@ahmadawais are you happy now?
